#From other source
#use chroot = no
#max verbosity = 2
#log file = /var/log/rsyncd.log
#[RASPBERRY-PI]
#path = /home/backsyno
#auth users = backsyno
#secrets file = /home/backsyno/rsyncd.secrets
#comment = Synchro fichiers avec le PI
#read only = false

uid = rsync
gid = rsync

[backup-stationmir]
        path = /mnt/backup/stationmir
        comment = Backup du synology stationmir
        read only = false