uid = root
gid = root
max connections = 4
syslog facility = local5
pid file = /var/run/rsyncd.pid
strict modes = false
hosts allow = *

[backup]
        path = /data
        comment = Synology NAS Backup Target
        read only = false
        auth users = bestwave
        secrets file = /etc/rsyncd.secrets
        list = yes