include:
  - ./config/nginx/docker-compose.nginx.yaml
#  - ./config/onlyoffice/docker-compose.onlyoffice.yaml
  - ./config/collabora/docker-compose.collabora.yaml
#  - ./config/sync-in-desktop-releases/docker-compose.sync-in-desktop-releases.yaml

name: sync-in
services:
  sync_in:
    image: syncin/server:2
    container_name: sync-in
    restart: always
    environment:
      - INIT_ADMIN
      - INIT_ADMIN_PASSWORD
      - INIT_ADMIN_LOGIN
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "8080:8080"
    volumes:
      - ./environment.yaml:/app/environment/environment.yaml
      - /mnt/data/cloud/sync-in:/app/data
      - desktop_releases:/app/static/releases:ro
    depends_on:
      mariadb:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "5"
    networks:
      - sync_in_network

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    command: --innodb_ft_cache_size=16000000 --max-allowed-packet=1G
    environment:
      MYSQL_ROOT_PASSWORD: MySQLRootPassword
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: sync_in
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sync_in_network

networks:
  sync_in_network:
    driver: bridge

volumes:
  mariadb_data:
  desktop_releases:
