# TA 30/12/2025 Modified to fit my needs : 
snapshot_dir               mnt/data/@snapshots
snapshot_create            onchange

snapshot_preserve          8h 7d 0w 1m 1y
snapshot_preserve_min      latest
target_preserve            8h 7d 0w 1m 1y
target_preserve_min        latest

volume /
  subvolume mnt/data/backup/internal
  subvolume mnt/data/immich
  subvolume mnt/data/cloud
  subvolume mnt/data/servarr/media/movies
  subvolume mnt/data/servarr/media/tv
  subvolume mnt/data/servarr/media/books
  subvolume mnt/data/servarr/media/audiobooks
  subvolume mnt/data/servarr/media/audio
