# TA 30/12/2025 For remote push to mordor
ssh_identity /etc/btrbk/ssh/id_rsa
snapshot_dir               mnt/data/@snapshots
snapshot_create            onchange

snapshot_preserve          8h 7d 0w 1m 1y
snapshot_preserve_min      latest
target_preserve            8h 7d 0w 1m 1y
target_preserve_min        latest

volume /
  subvolume mnt/data/backup/internal
    target ssh://192.168.1.6/mnt/backup/shire
  subvolume mnt/data/immich
    target ssh://192.168.1.6/mnt/backup/shire
  subvolume mnt/data/cloud
    target ssh://192.168.1.6/mnt/backup/shire
  subvolume mnt/data/servarr/media/movies
    target ssh://192.168.1.6/mnt/backup/shire
  subvolume mnt/data/servarr/media/tv
    target ssh://192.168.1.6/mnt/backup/shire
  subvolume mnt/data/servarr/media/books
    target ssh://192.168.1.6/mnt/backup/shire
  subvolume mnt/data/servarr/media/audiobooks
    target ssh://192.168.1.6/mnt/backup/shire
  subvolume mnt/data/servarr/media/audio
    target ssh://192.168.1.6/mnt/backup/shire